
sudo: required

dist: trusty

language: haskell

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.stack/

before_install:
- docker build -t verbs .
- docker images -a
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --skip-ghc-check setup
- stack build --no-terminal --skip-ghc-check --only-snapshot

script:
- stack --no-terminal --skip-ghc-check test
